# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - hassans-backend-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Build with gradle wrapper
      run: gradle build

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'hassans-backend-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6bc6fbbce2d5400aac487c79cd53ac32 }}
        package: '${{ github.workspace }}/build/libs/*.jar'
